---
- name: Install deal.II and the preCICE deal.II adapter
  hosts: all
  become: true

  vars:
    adapter_repo_url: "https://github.com/precice/dealii-adapter.git"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install libdeal.ii-dev package
      apt:
        name: libdeal.ii-dev
        state: present

    - name: Set adapter path using actual user directory
      set_fact:
        adapter_path: "{{ lookup('env', 'HOME') }}/dealii-adapter"
      become: false

    - name: Debug adapter path
      become: false
      debug:
        msg: "Adapter will be cloned to: {{ adapter_path }}"

    - name: Clone deal.II adapter repo if not present
      become: false
      git:
        repo: "{{ adapter_repo_url }}"
        dest: "{{ adapter_path }}"
        version: master
        depth: 1
        update: yes

    - name: Build the deal.II adapter
      become: false
      shell: |
        cmake .
        make -j $(nproc)
      args:
        chdir: "{{ adapter_path }}"
        executable: /bin/bash

    - name: Add deal.II adapter path to PATH in .bashrc
      become: false
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: 'export PATH="{{ adapter_path }}:${PATH}"'
        insertafter: EOF
